# Семинар 1

In [5]:
a =[]
a.append(1)
a

[1]


$$
MSE = (1/l) * \sum_{i=1}^{l} (a(x_i) - y_i)^2
$$


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки. 

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка" 
- `y` - изменить тип выбранной ячейки на "код" 
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [6]:
2 + 2

4

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [7]:
import numpy as np

In [8]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [9]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [11]:
vec.dtype

dtype('int32')

In [12]:
type(vec)

numpy.ndarray

Размер массива:

In [13]:
vec.shape

(3, 2)

Число осей:

In [14]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [15]:
np.sum(vec)

21

In [16]:
np.sum(vec, axis=0)

array([ 9, 12])

axis = 0
Вдоль строк
axis = 1
Вдоль столбцов

In [17]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [18]:
vec.sum()

21

Транспонируем массив:

In [19]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [21]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [41]:
vec
vec.shape

(3, 2)

In [44]:
%%time
vec.reshape(2, 3)

Wall time: 0 ns


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
%%time
vec.reshape(-1, 3)

Wall time: 0 ns


array([[1, 2, 3],
       [4, 5, 6]])

reshape(-1, x) - **позволяет преобразвать матрицу, если неизвестна одна из размерностей**

In [24]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [45]:
vec


array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
vec[0, 1]

2

Сначала строка, потом столбец

In [25]:
vec[:, 1]

array([2, 4, 6])

In [26]:
vec[2, :]

array([5, 6])

In [27]:
vec[1:2, 0]

array([3])

In [28]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [51]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [30]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [31]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [32]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [33]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [34]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [53]:
vec
vec.shape

(3, 2)

In [56]:
vec.dot(vec ** 2)

vec @ vec ** 2

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [59]:
vec.dot(vec.reshape(-1, 3) ** 2)
# reshape != transpose

array([[ 33,  54,  81],
       [ 67, 112, 171],
       [101, 170, 261]])

In [58]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [ ]:
vec @ (vec ** 2).T

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [60]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [62]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Broadcasting - угадывание нампаем арифметической операции
 
 
**опасная практика**

In [63]:
vec + np.arange(3)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Булевы массивы:

In [64]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [65]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [66]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [71]:
a = np.zeros((2, 3))

Массив из единиц:

In [72]:
a.dtype

dtype('float64')

In [73]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [75]:
np.diagonal(np.identity(5))

array([1., 1., 1., 1., 1.])

Массивы можно объединять:

In [76]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [78]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [87]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [82]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [89]:
np.random.randn(3, 2)

array([[ 0.0169049 , -0.51498352],
       [ 0.24450929, -0.18931261],
       [ 2.67217242,  0.46480249]])

In [ ]:
np.random.normal(2, 1, size=3)

In [ ]:
np.random.randint(5, 10, size=3)

Почему вообще используют `numpy`?

In [90]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [91]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

Wall time: 18 s


In [92]:
%%time
C = A @ B

Wall time: 7.98 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐

In [102]:
#1
arr = np.array([2, 54, 3, 653, 32])
arr

array([  2,  54,   3, 653,  32])

In [103]:
#2
reversearr = arr[::-1]
reversearr

array([ 32, 653,   3,  54,   2])

In [104]:
noteven = arr[arr % 2 != 0].max()
noteven

653

In [109]:
#3
fav = 10
arr[arr % 2 != 0] = fav
arr

array([ 2, 54, 10, 10, 32])

In [113]:
#4
n = 5
newarr = np.arange(2 * n - 1, 0, -2)
#newarr = newarr[newarr % 2 != 0][:: -1]
newarr

array([9, 7, 5, 3, 1])

In [124]:
#5
array = np.arange(5)
array
n = 1.33
print('Min =', np.argmin(np.abs(array - n)))
print('Max =', np.argmax(np.abs(array - n)))

Min = 1
Max = 4


In [139]:
#6
def problem6(coef, const):
    coef = np.append(coef, const)
    powers = np.arange(len(coef))[::-1]
    powers[-1] = 1
    
    return coef / powers
    

In [140]:
problem6(np.array([4, 6,  0, 1]), -2)

array([ 1.,  2.,  0.,  1., -2.])

In [141]:
#7
def derivative(coef, point):
    coef = coef[:-1]
    powers = np.arange(len(coef))[::-1]
    
    powers += 1
    # Не создается копия объекта (Более оптимально)
    
    derivative_coef = powers * coef
    
    return derivative_coef, np.sum(derivative_coef * point ** (powers - 1))

In [142]:
derivative(np.array([1, 2, 0, 1, -2]), 1) 

(array([4, 6, 0, 1]), 11)